# Generated by Django 5.0.3 on 2024-03-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchgame',
            name='match_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
