# Generated by Django 5.0.3 on 2024-03-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_matchgame_match_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchgame',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='matchgame',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
