# Generated by Django 5.0.3 on 2024-03-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_team_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['matches_won', 'matches_drawn', 'team']},
        ),
        migrations.AddField(
            model_name='stat',
            name='goal_difference',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchgame',
            name='away_team_scores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchgame',
            name='home_team_scores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='matches_drawn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='matches_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='matches_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='matches_won',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
