# Generated by Django 5.0.3 on 2024-03-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_stat_goals_against_stat_goals_for'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['-matches_won', 'matches_drawn', 'team']},
        ),
        migrations.AddField(
            model_name='stat',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
